version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  node:
    build: .
    ports:
      - "3000:3000"
    working_dir: /shellshare
    environment:
      - MONGOLAB_URI=mongodb://mongo:27017/shellshare
      - NODE_ENV=production
      # - HOST=
    depends_on:
      - mongo
